<?php

namespace AppBundle\Repository;

/**
 * anilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anilRepository extends \Doctrine\ORM\EntityRepository
{
}
