<?php

namespace AppBundle\Repository;

/**
 * itqbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class itqbRepository extends \Doctrine\ORM\EntityRepository
{
}
