<?php

namespace AppBundle\Repository;

/**
 * itqb3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class itqb3Repository extends \Doctrine\ORM\EntityRepository
{
}
